{
  "name": "async-future",
  "description": "A powerful and yet simple futures library for javascript in node.js and in-browser.",
  "keywords": [
    "future",
    "promise",
    "deferred",
    "async",
    "parallel",
    "thread",
    "concurrency"
  ],
  "version": "1.0.2",
  "main": "asyncFuture.js",
  "author": {
    "name": "Billy Tetrud",
    "email": "bitetrudpublic@gmail.com",
    "url": "https://github.com/fresheneesz/"
  },
  "license": {
    "name": "MIT",
    "url": "http://www.opensource.org/licenses/mit-license.php"
  },
  "repository": {
    "type": "git",
    "url": "git://github.com/fresheneesz/asyncFuture"
  },
  "dependencies": {
    "trimArguments": "https://github.com/fresheneesz/trimArguments/archive/e69ed3ebdfe6cf055916ba6e3a1e4b28f696da6f.tar.gz"
  },
  "devDependencies": {
    "deadunit": "5.1.4",
    "build-modules": "1.0.8"
  },
  "scripts": {
    "test": "node test/asyncFuturesTest.js"
  },
  "readme": "`async-future`\n============\n\nA simple, powerful library for managing asynchronous control flow and saner handling of asynchronous exceptions in `node.js` and the `browser`.\n\nWhy use async-future?\n=====================\n* If you want to avoid callback-hell\n* If you want exception bubbling with try-catch-finally semantics for asynchronous code\n* If you ever need to wait for two or more asynchronous calls to complete before executing some code\n\nExamples\n=======\n\nSimple return with error handling\n```javascript\nvar Future = require('async-future')  // node.js and webpack\n\nvar f = new Future\nasynchronousFunction(function(result) {\n    if(error) f.throw(error)\n    else      f.return(result)\n})\n\nf.then(function(result) {\n   useThe(result)\n\n}).catch(function(e) {\n   console.error(\"Oh no! \"+error)\n\n}).done()\n```\n\nImmediates, familar try-catch-finally semantics, and Future.wrap\n```javascript\n\nvar f2 = Future(45) // you can create immediately-resolved futures for convenience\nvar f3 = Future(undefined) // note that undefined has to be explicitly passed in\n                           // so \"Future()\" won't work the same way\nvar futureFn2 = Future.wrap(asyncFn2) // turns an asynchronous function into a function\n                                      // that returns a future\nf2.then(function(result) {\n    console.log(result) // prints 45\n    return Future(true) // returning a future passes the result of the future (in this\n                        // case 45) to the next `then` statement\n}).then(function(result2) {\n    console.log(result2) // prints true\n    return futureFn2(result2) // using the wrapped function is just like using the\n                              // unwrapped function, but without the callback parameter\n}).finally(function() {\n    // this is ran regardless of whether an exception was thrown above ^\n\n}).catch(function(e){  // unlike try-catch semantics, `catch` should come after `finally`\n\n}).done() // ensures that any exception still in the pipes here is asynchronously thrown\n         // (instead of being lost). This is equivalent to 'detatch' in fibers/future\n\nfunction asyncFn2(parameter, /*more parameters if you want, */ callback) {\n    try {\n       callback(undefined, doStuff(parameter))\n    } catch(e) {\n       callback(e)\n    }\n}\n```\n\nWhy use async-future over ...\n=============================\n* Has familiar and well understood try-catch-finally semantics\n* [jQuery deferred](http://api.jquery.com/jQuery.Deferred/) doesn't bubble exceptions\n* [Q promises](https://github.com/kriskowal/q) doesn't give you the flexibility to resolve your promises, rather it splits things into promises and deffereds. This makes things both more complicated and more restrictive.\n* [fibers/future](https://github.com/laverdet/node-fibers) has a nicer interface, but only works on node.js\n* [FutureJs](https://github.com/FuturesJS/FuturesJS) doesn't have very good documentation (so its hard to really know)\n* [parallel.js](http://adambom.github.io/parallel.js/) is more complicated and doesn't help you bubble exceptions\n* [substack's node-seq](https://github.com/substack/node-seq) is also much more complicated, and doesn't have sane semantics for passing futures/promises out of functions\n\nInstall\n=======\n\n```\nnpm install async-future\n```\n\nUsage\n=====\n\n```javascript\nvar Future = require('async-future')\n```\n\nfuture-chains\n-------------\n\nThe most important part of `async-future` is future-chains. \nThese are chains that have try-catch-finally style semantics, but are asynchronous.\nFuture-chains consist of chains of `then`, `catch`, and `finally` calls and must always eventually end in a `done` call. When an exception is thrown (or an error-resolved future is returned) from a previous link in the chain, the error propagates down the chain to the first catch it comes across, skipping any `then`s and running any `finally`s.\n\nThe  methods `then`, `catch`, and `finally` return a `new Future` that is resolved when their callback completes. The future returned by all three of these methods will resolve with an error if an exception is thrown from the callbacks.\n\nThe future returned by the methods `then` and `catch` will resolve to the following return values (non-errors):\n\n* `undefined`, if the callback returns `undefined` (ie nothing), or\n* if the callback returns a `Future` object, it resolves to the value that future resolves to\n\n*Other than `undefined`, you may not return a value that isn't a `Future` object from these callbacks.*\n\n`f.then(<callback>)` - executes `<callback>` if `f` is returned from. `<callback>` gets the return value of `f` as its only parameter. Returns a future that resolves when `then` completes or if `f` is resolved with an error. Does not execute the callback if `f` resolves to an error, but instead resolves its return value with the error from `f`.\n\n`f.catch(<callback>)` - executes `<callback>` if `f` is thrown from. `<callback>` gets the error value of `f` as its only parameter. Returns a future that resolves when its callback completes or when `f` is returned from. Does not execute the callback if `f` resolves to a return value, but instead resolves its return value with the return value of `f`.\n\n`f.finally(<callback>)` - executes a callback when `f` resolves, regardless of whether `f` was resolved with a return value or an error. The callback takes no arguments. Returns a future that resolves when `<callback>` completes or when the future it returns completes. If the future `<callback>` returns resolves to an exception, the future returned from `finally` will too. If the future `<callback>` returns resolves to a return value, or if `<callback>` returns `undefined`, the future `finally` returns will resolves to the same result as `f`.\n\n`f.done()` - marks a future chain as done, which means that if any subsequent exceptions happen, \n it will be thrown asynchronously (and likely caught by a domain if its node.js, or by window.onerror in browsers). \nEvery future or future-chain that won't have one of the chain-methods (or the `resolver` method) called on it, \nshould call `.done()`, so that thrown exceptions won't get lost.\n\n**Summary**\n\n.                                      | then                       | catch                         | finally\n-------------------------------------: | -------------------------- | ----------------------------- | -------------\n**parameter**                        | value of calling future    | exception from calling future  | none\n**returned future resolves to**     | *returned* future's value  | *returned* future's value     | thrown exception or *calling* future's value\n**exceptions thrown in callback**   | propogate                  | propogate                    | propogate\n\n\nOther Instance properties\n-------------------\n\n`f.return(<value>)` - resolves a future with a return value (`undefined` if a value isn't passed)\n\n`f.throw(<exception>)` - resolves a future with an exception\n\n`f.resolver()` - returns an errback from a future. This is useful for using functions that require an errback-style callback (a function that takes two parameters, `(error, result)`)\n\n`f.resolved()` - returns true if the future has already been resolved, false otherwise.\n\nStatic properties\n-----------------\n\n`Future.all(<futures>` - returns a future that resolves when all futures inside resolve (or throws an error when one of the futures returns an error).\n\n`Future.wrap(<fn>)` - wraps a function that takes an errback so that it returns a future instead of calling an errback.\n\n`Future.isLikeAFuture(<fn>)` - Returns true if the object looks like a future (duck typing). You might want to use this instead of `instanceof` because its possible that you might have different versions of async-future floating around (in which case `instanceof` might not work like you expect).\n\nExample:\n\n```javascript\nfunction a(x, errback) {\n\tif(x === false)\n\t\terrback(Error('x isnt true : ('))\n\telse\n\t\terrback(undefined, x)\n}\n\nvar aFuture = Future.wrap(a)\n\n// prints 5\naFuture(5).then(function(result) {\n\tconsole.log(result)\n}).done()\n\n// prints an exception\naFuture(false).then(function(result) {\n\tconsole.log(result) // never gets here\n}).done()\n\n```\n\n`Future.wrap(<object>, <method)` - wraps a method that takes an errback so that it returns a future instead of calling an errback. Example:\n\n* Example: `var wrappedMethod = Future.wrap(object, 'methodName')`\n\n`Future.error(<handler>)` - sets up a function that is called when an unhandled error happens. `<handler>` gets one parameter, the unhandled exception. Unhandled errors happen when `done` is called and an exception is thrown from the future.\n\n`Future.debug` - if true, gives each future a unique id (default is `false`)\n\n\nTodo\n====\n\n\n* Long stack traces (where possible)\n* Think about how to handle domains - right now `done` throws into whatever domain the beggining of the chain was called in, instead of the context `done` was called in\n * This might be ok since `done` is intended to be a safety net, and not generally used to catch and report errors\n* Standalone bundle (via ) [build-modules](https://github.com/fresheneesz/buildModules)\n* timeout or cancelation (probably cancellation is more general)\n\nChangelog\n========\n\n* 1.0.2 - adding code to prevent \"too much recursion\" RangeErrors from being caused by code with a ridiculous number of chained `then`s using a setTimeout every 400th chain\n* 1.0.1 - fixing obscure bug in `catch`\n* 1.0.0 - making a simple change that hugely improves performance at the cost of making it a little more impportant when exactly you call `return` or `throw` (though that also has the upside of allowing more control)\n* 0.1.18 - fixing bug in `finally` where exceptions and results weren't being correctly passed through\n* 0.1.16 - fixing behavior when exceptions happen in a finally block\n* 0.1.10 - fixing another (i think the last) related bug where finally was being called before a future returned by a previous `then` callback was resolved\n* 0.1.9 - fixing related bug with futures returned from a `then` callback, where exceptions weren't being properly propogated\n* 0.1.8 - fixing bug with the `done` method when a future with an error is returned from a `then` callback\n\nHow to Contribute!\n============\n\nAnything helps:\n\n* Creating issues (aka tickets/bugs/etc). Please feel free to use issues to report bugs, request features, and discuss changes\n* Updating the documentation: ie this readme file. Be bold! Help create amazing documentation!\n* Submitting pull requests.\n\nHow to submit pull requests:\n\n1. Please create an issue and get my input before spending too much time creating a feature. Work with me to ensure your feature or addition is optimal and fits with the purpose of the project.\n2. Fork the repository\n3. clone your forked repo onto your machine and run `npm install` at its root\n4. If you're gonna work on multiple separate things, its best to create a separate branch for each of them\n5. edit!\n6. If it's a code change, please add to the unit tests (at test/asyncFuturesTest.js) to verify that your change\n7. When you're done, run the unit tests and ensure they all pass\n8. Commit and push your changes\n9. Submit a pull request: https://help.github.com/articles/creating-a-pull-request\n\nContributors\n============\n* Special thanks to [kriskowal](kriskowal), who's project [Q promises](qPromises) gave me inspiration for this project.\n\n[jayferd]: https://github.com/kriskowal\n[qPromises]: https://github.com/kriskowal/q\n\nLicense\n=======\nReleased under the MIT license: http://opensource.org/licenses/MIT\n",
  "readmeFilename": "README.md",
  "bugs": {
    "url": "https://github.com/fresheneesz/asyncFuture/issues"
  },
  "_id": "async-future@1.0.2",
  "_shasum": "f715b12ed87dd472e09dcd629b769e90572b34d9",
  "_from": "https://registry.npmjs.org/async-future/-/async-future-1.0.2.tgz",
  "_resolved": "https://registry.npmjs.org/async-future/-/async-future-1.0.2.tgz"
}
